"""Initial migration

Revision ID: e5accbe38c59
Revises:
Create Date: 2025-06-15 09:56:57.729855

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5accbe38c59"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "machines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_machines_identifier"), "machines", ["identifier"], unique=True
    )
    op.create_table(
        "operators",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "store_paths",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("closure_size", sa.Integer(), nullable=False),
        sa.Column("nar_size", sa.Integer(), nullable=False),
        sa.Column("deriver", sa.String(), nullable=True),
        sa.Column("nar_hash", sa.String(), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_store_paths_deriver"), "store_paths", ["deriver"], unique=False
    )
    op.create_index(
        op.f("ix_store_paths_nar_hash"), "store_paths", ["nar_hash"], unique=False
    )
    op.create_index(op.f("ix_store_paths_path"), "store_paths", ["path"], unique=True)
    op.create_table(
        "deployments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("operator_id", sa.String(), nullable=False),
        sa.Column("target_machine_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("toplevel", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.name"],
        ),
        sa.ForeignKeyConstraint(
            ["target_machine_id"],
            ["machines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployments_toplevel"), "deployments", ["toplevel"], unique=False
    )
    op.create_table(
        "store_path_references",
        sa.Column("referrer_id", sa.Integer(), nullable=False),
        sa.Column("referenced_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["referenced_id"],
            ["store_paths.id"],
        ),
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["store_paths.id"],
        ),
        sa.PrimaryKeyConstraint("referrer_id", "referenced_id"),
        sa.UniqueConstraint("referrer_id", "referenced_id", name="unique_dependencies"),
    )
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("trigger_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trigger_id"],
            ["machines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "store_paths_closures",
        sa.Column("store_path_id", sa.Integer(), nullable=False),
        sa.Column("deployment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_path_id"],
            ["store_paths.id"],
        ),
        sa.PrimaryKeyConstraint("store_path_id", "deployment_id"),
        sa.UniqueConstraint(
            "store_path_id", "deployment_id", name="unique_closure_per_deployment"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("store_paths_closures")
    op.drop_table("webhooks")
    op.drop_table("store_path_references")
    op.drop_index(op.f("ix_deployments_toplevel"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(op.f("ix_store_paths_path"), table_name="store_paths")
    op.drop_index(op.f("ix_store_paths_nar_hash"), table_name="store_paths")
    op.drop_index(op.f("ix_store_paths_deriver"), table_name="store_paths")
    op.drop_table("store_paths")
    op.drop_table("operators")
    op.drop_index(op.f("ix_machines_identifier"), table_name="machines")
    op.drop_table("machines")
    # ### end Alembic commands ###
