"""empty message

Revision ID: ffd4f0caba12
Revises: a9c836480f93
Create Date: 2025-06-22 10:49:00.986045

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffd4f0caba12"
down_revision: Union[str, None] = "a9c836480f93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("ALTER TABLE deployments ADD COLUMN size INTEGER NOT NULL DEFAULT 0")

    op.execute(
        "UPDATE deployments "
        "SET size = store_paths.closure_size "
        "FROM store_paths "
        "WHERE deployments.toplevel = store_paths.path"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deployments", "size")
    # ### end Alembic commands ###
